### ISSUE TITLE
Could not create folder

### ISSUE THREAD

**Issue by st3iny** [nextcloud/previewgenerator#289]
I had a similar issue with Nextcloud 22.2.4: 

```
2022-02-06T10:01:50+00:00 In Folder.php line 173:
2022-02-06T10:01:50+00:00                                         
2022-02-06T10:01:50+00:00   [OCP\Files\NotPermittedException]     
2022-02-06T10:01:50+00:00   Could not create folder: {$fullPath}  
2022-02-06T10:01:50+00:00                                         
2022-02-06T10:01:50+00:00 
2022-02-06T10:01:50+00:00 Exception trace:
2022-02-06T10:01:50+00:00   at /var/www/html/lib/private/Files/Node/Folder.php:173
2022-02-06T10:01:50+00:00  OC\Files\Node\Folder->newFolder() at /var/www/html/lib/private/Files/AppData/AppData.php:156
2022-02-06T10:01:50+00:00  OC\Files\AppData\AppData->newFolder() at /var/www/html/lib/private/Preview/Storage/Root.php:74
2022-02-06T10:01:50+00:00  OC\Preview\Storage\Root->newFolder() at /var/www/html/lib/private/Preview/Generator.php:472
2022-02-06T10:01:50+00:00  OC\Preview\Generator->getPreviewFolder() at /var/www/html/lib/private/Preview/Generator.php:132
2022-02-06T10:01:50+00:00  OC\Preview\Generator->generatePreviews() at /var/www/html/lib/private/PreviewManager.php:204
2022-02-06T10:01:50+00:00  OC\PreviewManager->generatePreviews() at /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php:243
2022-02-06T10:01:50+00:00  OCA\PreviewGenerator\Command\Generate->parseFile() at /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php:214
2022-02-06T10:01:50+00:00  OCA\PreviewGenerator\Command\Generate->parseFolder() at /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php:212
2022-02-06T10:01:50+00:00  OCA\PreviewGenerator\Command\Generate->parseFolder() at /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php:212
2022-02-06T10:01:50+00:00  OCA\PreviewGenerator\Command\Generate->parseFolder() at /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php:212
2022-02-06T10:01:50+00:00  OCA\PreviewGenerator\Command\Generate->parseFolder() at /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php:183
2022-02-06T10:01:50+00:00  OCA\PreviewGenerator\Command\Generate->generatePathPreviews() at /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php:131
2022-02-06T10:01:50+00:00  OCA\PreviewGenerator\Command\Generate->execute() at /var/www/html/3rdparty/symfony/console/Command/Command.php:255
2022-02-06T10:01:50+00:00  Symfony\Component\Console\Command\Command->run() at /var/www/html/3rdparty/symfony/console/Application.php:1009
2022-02-06T10:01:50+00:00  Symfony\Component\Console\Application->doRunCommand() at /var/www/html/3rdparty/symfony/console/Application.php:273
2022-02-06T10:01:50+00:00  Symfony\Component\Console\Application->doRun() at /var/www/html/3rdparty/symfony/console/Application.php:149
2022-02-06T10:01:50+00:00  Symfony\Component\Console\Application->run() at /var/www/html/lib/private/Console/Application.php:209
2022-02-06T10:01:50+00:00  OC\Console\Application->run() at /var/www/html/console.php:99
2022-02-06T10:01:50+00:00  require_once() at /var/www/html/occ:11
```

I added a log output in 
nextcloud/lib/private/Files/Node/Folder.php:173: 
`throw new NotPermittedException('Could not create folder, fullPath: '.$fullPath.', path: '.$path);`

After i checked and the folder did exist for me. So to fix this i added a check on the creation if the folder already exists to fix this and changed it to: 
`                        if (!$this->get($path) || !$this->view->mkdir($fullPath)) {
                                throw new NotPermittedException('Could not create folder, fullPath: '.$fullPath.', path: '.$path);
                        }
`

_Originally posted by @f4t-t0ny in https://github.com/nextcloud/previewgenerator/issues/121#issuecomment-1030803305_

**Comment by skjnldsv** [comment]
Same issue

**Comment by stratege1401** [comment]
The idea of letting the process run to end, and logging the errors is nice...

**Comment by st3iny** [comment]
@f4t-t0ny @stratege1401 I think I found the problem and developed a patch. The problem is, that I'm not able to reproduce the issue locally. Could you test it for me?

**Comment by stratege1401** [comment]
I am ok to test and report... But only tomorrow...

**Comment by emptinessboy** [comment]
I meet the same problem

2022-04-27T12:02:26+00:00 
2022-04-27T12:02:26+00:00 In Folder.php line 173:
2022-04-27T12:02:26+00:00                            
2022-04-27T12:02:26+00:00   Could not create folder  
2022-04-27T12:02:26+00:00                            
2022-04-27T12:02:26+00:00 
2022-04-27T12:02:26+00:00 preview:generate-all [-p|--path [PATH]] [--] [<user_id>...]
2022-04-27T12:02:26+00:00

**Comment by emptinessboy** [comment]
> @f4t-t0ny @stratege1401我想我发现了问题并开发了一个补丁。问题是，我无法在本地重现该问题。你能帮我测试一下吗？
> 
> 补丁：[preview-duplicate-folder-creation.patch.txt](https://github.com/nextcloud/previewgenerator/files/8483200/preview-duplicate-folder-creation.patch.txt)

I tried this patch, it works ok now. I am running Nextcloud23.0 with preview plugin 4.0 on CentOS7,php8.

**Comment by MB-Finski** [comment]
> @f4t-t0ny @stratege1401 I think I found the problem and developed a patch. The problem is, that I'm not able to reproduce the issue locally. Could you test it for me?
> 
> Patch: [preview-duplicate-folder-creation.patch.txt](https://github.com/nextcloud/previewgenerator/files/8483200/preview-duplicate-folder-creation.patch.txt)

Can confirm, this patch fixed this issue for me.

**Comment by st3iny** [comment]
Thanks a lot for testing the patch. I'll submit it upstream.

**Comment by Blisk** [comment]
I have the same problem, don't know what this patch is and how it is used?

**Comment by st3iny** [comment]
It is already merged and released. The problem will be fixed if you are using Nextcloud >= 22 and installed the latest update.

**Comment by WolfsWelpe** [comment]
Hello I'm currently running Nextcloud 24.0.1.
I got the same error and have installed PreviewGenerator 5.0.0. 
I applied the patch but still get this error:

https://pastebin.com/GMxbyMZh

**Comment by rhyst** [comment]
I am using Nextcloud 24.0.6 and 5.0.1 of this app and also get this error when trying to run `php occ preview:generate-all`. Let me know what logs I could provide to help with this.

**Comment by Chuckame** [comment]
Same for me, nextcloud 25.0.3 (plugin 5.1.1) and 24.0.5 (forgot to take the version)

**Comment by Chuckame** [comment]
After a full reinstall, i don't have this error anymore

**Comment by zvarnes** [comment]
I'm running the most recent version version of this app, and Nextcloud and still getting this issue... 

> 2023-03-27T01:26:29+00:00 In Folder.php line 166:
2023-03-27T01:26:29+00:00
2023-03-27T01:26:29+00:00   [OCP\Files\NotPermittedException]
2023-03-27T01:26:29+00:00   Could not create folder
2023-03-27T01:26:29+00:00
2023-03-27T01:26:29+00:00
2023-03-27T01:26:29+00:00 Exception trace:
2023-03-27T01:26:29+00:00   at /var/www/nextcloud/lib/private/Files/Node/Folder.php:166
2023-03-27T01:26:29+00:00  OC\Files\Node\Folder->newFolder() at /var/www/nextcloud/lib/private/Files/AppData/AppData.php:147
2023-03-27T01:26:29+00:00  OC\Files\AppData\AppData->newFolder() at /var/www/nextcloud/lib/private/Preview/Storage/Root.php:74
2023-03-27T01:26:29+00:00  OC\Preview\Storage\Root->newFolder() at /var/www/nextcloud/lib/private/Preview/Generator.php:685
2023-03-27T01:26:29+00:00  OC\Preview\Generator->getPreviewFolder() at /var/www/nextcloud/lib/private/Preview/Generator.php:139
2023-03-27T01:26:29+00:00  OC\Preview\Generator->generatePreviews() at /var/www/nextcloud/lib/private/PreviewManager.php:212
2023-03-27T01:26:29+00:00  OC\PreviewManager->generatePreviews() at /var/www/nextcloud/apps/previewgenerator/lib/Command/PreGenerate.php:199
2023-03-27T01:26:29+00:00  OCA\PreviewGenerator\Command\PreGenerate->processFile() at /var/www/nextcloud/apps/previewgenerator/lib/Command/PreGenerate.php:177
2023-03-27T01:26:29+00:00  OCA\PreviewGenerator\Command\PreGenerate->processRow() at /var/www/nextcloud/apps/previewgenerator/lib/Command/PreGenerate.php:145
2023-03-27T01:26:29+00:00  OCA\PreviewGenerator\Command\PreGenerate->startProcessing() at /var/www/nextcloud/apps/previewgenerator/lib/Command/PreGenerate.php:113
2023-03-27T01:26:29+00:00  OCA\PreviewGenerator\Command\PreGenerate->execute() at /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php:255
2023-03-27T01:26:29+00:00  Symfony\Component\Console\Command\Command->run() at /var/www/nextcloud/3rdparty/symfony/console/Application.php:1009
2023-03-27T01:26:29+00:00  Symfony\Component\Console\Application->doRunCommand() at /var/www/nextcloud/3rdparty/symfony/console/Application.php:273
2023-03-27T01:26:29+00:00  Symfony\Component\Console\Application->doRun() at /var/www/nextcloud/3rdparty/symfony/console/Application.php:149
2023-03-27T01:26:29+00:00  Symfony\Component\Console\Application->run() at /var/www/nextcloud/lib/private/Console/Application.php:215
2023-03-27T01:26:29+00:00  OC\Console\Application->run() at /var/www/nextcloud/console.php:100
2023-03-27T01:26:29+00:00  require_once() at /var/www/nextcloud/occ:11
2023-03-27T01:26:29+00:00
2023-03-27T01:26:29+00:00 preview:pre-generate
2023-03-27T01:26:29+00:00

**Comment by st3iny** [comment]
@zvarnes Did you apply said patch manually at some point in the past?

**Comment by zvarnes** [comment]
@st3iny No I did not.

**Comment by AndyXheli** [comment]
Still an issue on NC 26.0.0

```{"reqId":"C9cREwf8AoxLPgLYppzf","level":3,"time":"2023-03-27T21:57:43-05:00","remoteAddr":"10.241.202.173","user":"ixheli","app":"index","method":"GET","url":"/apps/photos/api/v1/preview/978628?etag=bc17f3e333f5a2b73aaa6d7b095162fd&x=512&y=512","message":"Could not create folder","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36","version":"26.0.0.11","exception":{"Exception":"OCP\\Files\\NotPermittedException","Message":"Could not create folder","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/Files/AppData/AppData.php","line":147,"function":"newFolder","class":"OC\\Files\\Node\\Folder","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/Storage/Root.php","line":74,"function":"newFolder","class":"OC\\Files\\AppData\\AppData","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/Generator.php","line":685,"function":"newFolder","class":"OC\\Preview\\Storage\\Root","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/Generator.php","line":139,"function":"getPreviewFolder","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/Generator.php","line":116,"function":"generatePreviews","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/nextcloud/lib/private/PreviewManager.php","line":192,"function":"getPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/nextcloud/apps/photos/lib/Controller/PreviewController.php","line":162,"function":"getPreview","class":"OC\\PreviewManager","type":"->"},{"file":"/var/www/nextcloud/apps/photos/lib/Controller/PreviewController.php","line":128,"function":"fetchPreview","class":"OCA\\Photos\\Controller\\PreviewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"index","class":"OCA\\Photos\\Controller\\PreviewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1055,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Files/Node/Folder.php","Line":166,"CustomMessage":"--"},"id":"642350c51ba48"}
```

**Comment by CorneliousJD** [comment]
I just installed this app and am seeing the same issue running 
`docker exec -u www-data Nextcloud ./occ preview:generate-all -vvv`

```
2023-04-18T18:56:38+00:00 
2023-04-18T18:56:38+00:00 In Folder.php line 166:
2023-04-18T18:56:38+00:00                                      
2023-04-18T18:56:38+00:00   [OCP\Files\NotPermittedException]  
2023-04-18T18:56:38+00:00   Could not create folder            
2023-04-18T18:56:38+00:00                                      
2023-04-18T18:56:38+00:00 
2023-04-18T18:56:38+00:00 Exception trace:
2023-04-18T18:56:38+00:00   at /var/www/html/lib/private/Files/Node/Folder.php:166
2023-04-18T18:56:38+00:00  OC\Files\Node\Folder->newFolder() at /var/www/html/lib/private/Files/AppData/AppData.php:147
2023-04-18T18:56:38+00:00  OC\Files\AppData\AppData->newFolder() at /var/www/html/lib/private/Preview/Storage/Root.php:74
2023-04-18T18:56:38+00:00  OC\Preview\Storage\Root->newFolder() at /var/www/html/lib/private/Preview/Generator.php:685
2023-04-18T18:56:38+00:00  OC\Preview\Generator->getPreviewFolder() at /var/www/html/lib/private/Preview/Generator.php:139
2023-04-18T18:56:38+00:00  OC\Preview\Generator->generatePreviews() at /var/www/html/lib/private/PreviewManager.php:212
2023-04-18T18:56:38+00:00  OC\PreviewManager->generatePreviews() at /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php:230
2023-04-18T18:56:38+00:00  OCA\PreviewGenerator\Command\Generate->parseFile() at /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php:212
2023-04-18T18:56:38+00:00  OCA\PreviewGenerator\Command\Generate->parseFolder() at /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php:210
2023-04-18T18:56:38+00:00  OCA\PreviewGenerator\Command\Generate->parseFolder() at /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php:210
2023-04-18T18:56:38+00:00  OCA\PreviewGenerator\Command\Generate->parseFolder() at /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php:210
2023-04-18T18:56:38+00:00  OCA\PreviewGenerator\Command\Generate->parseFolder() at /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php:190
2023-04-18T18:56:38+00:00  OCA\PreviewGenerator\Command\Generate->generateUserPreviews() at /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php:136
2023-04-18T18:56:38+00:00  OCA\PreviewGenerator\Command\Generate->OCA\PreviewGenerator\Command\{closure}() at /var/www/html/lib/private/User/Manager.php:639
2023-04-18T18:56:38+00:00  OC\User\Manager->callForSeenUsers() at /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php:137
2023-04-18T18:56:38+00:00  OCA\PreviewGenerator\Command\Generate->execute() at /var/www/html/custom_apps/recognize/vendor/symfony/console/Command/Command.php:298
2023-04-18T18:56:38+00:00  Symfony\Component\Console\Command\Command->run() at /var/www/html/custom_apps/recognize/vendor/symfony/console/Application.php:1040
2023-04-18T18:56:38+00:00  Symfony\Component\Console\Application->doRunCommand() at /var/www/html/custom_apps/recognize/vendor/symfony/console/Application.php:301
2023-04-18T18:56:38+00:00  Symfony\Component\Console\Application->doRun() at /var/www/html/custom_apps/recognize/vendor/symfony/console/Application.php:171
2023-04-18T18:56:38+00:00  Symfony\Component\Console\Application->run() at /var/www/html/lib/private/Console/Application.php:215
2023-04-18T18:56:38+00:00  OC\Console\Application->run() at /var/www/html/console.php:100
2023-04-18T18:56:38+00:00  require_once() at /var/www/html/occ:11
2023-04-18T18:56:38+00:00 
2023-04-18T18:56:38+00:00 preview:generate-all [-p|--path [PATH]] [--] [<user_id>...]
2023-04-18T18:56:38+00:00 
```

**Comment by arcoast** [comment]
I'm also seeing this on v5.2.4 on Nextcloud v26.0.0

Running `occ preview:generate-all -vvv`

```bash
2023-05-01T17:20:10+00:00 
2023-05-01T17:20:10+00:00 In Folder.php line 166:
2023-05-01T17:20:10+00:00                                      
2023-05-01T17:20:10+00:00   [OCP\Files\NotPermittedException]  
2023-05-01T17:20:10+00:00   Could not create folder            
2023-05-01T17:20:10+00:00                                      
2023-05-01T17:20:10+00:00 
2023-05-01T17:20:10+00:00 Exception trace:
2023-05-01T17:20:10+00:00   at /config/www/nextcloud/lib/private/Files/Node/Folder.php:166
2023-05-01T17:20:10+00:00  OC\Files\Node\Folder->newFolder() at /config/www/nextcloud/lib/private/Files/AppData/AppData.php:147
2023-05-01T17:20:10+00:00  OC\Files\AppData\AppData->newFolder() at /config/www/nextcloud/lib/private/Preview/Storage/Root.php:74
2023-05-01T17:20:10+00:00  OC\Preview\Storage\Root->newFolder() at /config/www/nextcloud/lib/private/Preview/Generator.php:685
2023-05-01T17:20:10+00:00  OC\Preview\Generator->getPreviewFolder() at /config/www/nextcloud/lib/private/Preview/Generator.php:139
2023-05-01T17:20:10+00:00  OC\Preview\Generator->generatePreviews() at /config/www/nextcloud/lib/private/PreviewManager.php:212
2023-05-01T17:20:10+00:00  OC\PreviewManager->generatePreviews() at /config/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php:230
2023-05-01T17:20:10+00:00  OCA\PreviewGenerator\Command\Generate->parseFile() at /config/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php:212
2023-05-01T17:20:10+00:00  OCA\PreviewGenerator\Command\Generate->parseFolder() at /config/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php:210
2023-05-01T17:20:10+00:00  OCA\PreviewGenerator\Command\Generate->parseFolder() at /config/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php:210
2023-05-01T17:20:10+00:00  OCA\PreviewGenerator\Command\Generate->parseFolder() at /config/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php:210
2023-05-01T17:20:10+00:00  OCA\PreviewGenerator\Command\Generate->parseFolder() at /config/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php:210
2023-05-01T17:20:10+00:00  OCA\PreviewGenerator\Command\Generate->parseFolder() at /config/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php:190
2023-05-01T17:20:10+00:00  OCA\PreviewGenerator\Command\Generate->generateUserPreviews() at /config/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php:136
2023-05-01T17:20:10+00:00  OCA\PreviewGenerator\Command\Generate->OCA\PreviewGenerator\Command\{closure}() at /config/www/nextcloud/lib/private/User/Manager.php:639
2023-05-01T17:20:10+00:00  OC\User\Manager->callForSeenUsers() at /config/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php:137
2023-05-01T17:20:10+00:00  OCA\PreviewGenerator\Command\Generate->execute() at /config/www/nextcloud/3rdparty/symfony/console/Command/Command.php:255
2023-05-01T17:20:10+00:00  Symfony\Component\Console\Command\Command->run() at /config/www/nextcloud/3rdparty/symfony/console/Application.php:1009
2023-05-01T17:20:10+00:00  Symfony\Component\Console\Application->doRunCommand() at /config/www/nextcloud/3rdparty/symfony/console/Application.php:273
2023-05-01T17:20:10+00:00  Symfony\Component\Console\Application->doRun() at /config/www/nextcloud/3rdparty/symfony/console/Application.php:149
2023-05-01T17:20:10+00:00  Symfony\Component\Console\Application->run() at /config/www/nextcloud/lib/private/Console/Application.php:215
2023-05-01T17:20:10+00:00  OC\Console\Application->run() at /config/www/nextcloud/console.php:100
2023-05-01T17:20:10+00:00  require_once() at /config/www/nextcloud/occ:11
2023-05-01T17:20:10+00:00 
2023-05-01T17:20:10+00:00 preview:generate-all [-p|--path [PATH]] [--] [<user_id>...]
2023-05-01T17:20:10+00:00 
```

**Comment by arcoast** [comment]
Just to update, I ran the scan for each user separately and it seems to have done the trick and I can't reproduce the above any longer.

**Comment by zvarnes** [comment]
Still getting this error on version 26.0.1

**Comment by SchoolGuy** [comment]
I was able to trigger this bug with executing two `preview:generate-all` in parallel on accident.

NC 26.0.2 and Preview Generator 5.3.0

**Comment by maxkratz** [comment]
This issue also occurs on my Nextcloud instance (v25.0.12). Is there any ETA for a fix?

**Comment by JOHLC** [comment]
I am also seeing this.
Installation: Nextcloud VM 
Nextcloud version: 27.1.3 
Preview generator version: 5.3.0

It seems to get through 974 files/folders or more before erroring out, and seems to always be on the same folder.
A reinstall of the app didn't resolve it. 

```
sudo -u www-data php /var/www/nextcloud/occ preview:generate-all
```

[...]


```
2023-11-22T03:08:01+00:00 Generating previews for /User/files/User/Pictures/Graphics/DC Pictures/GEDC0607.JPG
2023-11-22T03:08:01+00:00 
2023-11-22T03:08:01+00:00 In Folder.php line 162:
2023-11-22T03:08:01+00:00                                                                                 
2023-11-22T03:08:01+00:00   [OCP\Files\NotPermittedException]                                             
2023-11-22T03:08:01+00:00   Could not create folder "/appdata_ockpphbbu4qb/preview/6/9/0/5/c/3/3/867860"  
2023-11-22T03:08:01+00:00                                                                                 
2023-11-22T03:08:01+00:00 
2023-11-22T03:08:01+00:00 Exception trace:
2023-11-22T03:08:01+00:00   at /var/www/nextcloud/lib/private/Files/Node/Folder.php:162
2023-11-22T03:08:01+00:00  OC\Files\Node\Folder->newFolder() at /var/www/nextcloud/lib/private/Files/AppData/AppData.php:147
2023-11-22T03:08:01+00:00  OC\Files\AppData\AppData->newFolder() at /var/www/nextcloud/lib/private/Preview/Storage/Root.php:74
2023-11-22T03:08:01+00:00  OC\Preview\Storage\Root->newFolder() at /var/www/nextcloud/lib/private/Preview/Generator.php:607
2023-11-22T03:08:01+00:00  OC\Preview\Generator->getPreviewFolder() at /var/www/nextcloud/lib/private/Preview/Generator.php:139
2023-11-22T03:08:01+00:00  OC\Preview\Generator->generatePreviews() at /var/www/nextcloud/lib/private/PreviewManager.php:212
2023-11-22T03:08:01+00:00  OC\PreviewManager->generatePreviews() at /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php:230
2023-11-22T03:08:01+00:00  OCA\PreviewGenerator\Command\Generate->parseFile() at /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php:212
2023-11-22T03:08:01+00:00  OCA\PreviewGenerator\Command\Generate->parseFolder() at /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php:210
2023-11-22T03:08:01+00:00  OCA\PreviewGenerator\Command\Generate->parseFolder() at /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php:210
2023-11-22T03:08:01+00:00  OCA\PreviewGenerator\Command\Generate->parseFolder() at /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php:210
2023-11-22T03:08:01+00:00  OCA\PreviewGenerator\Command\Generate->parseFolder() at /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php:210
2023-11-22T03:08:01+00:00  OCA\PreviewGenerator\Command\Generate->parseFolder() at /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php:190
2023-11-22T03:08:01+00:00  OCA\PreviewGenerator\Command\Generate->generateUserPreviews() at /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php:136
2023-11-22T03:08:01+00:00  OCA\PreviewGenerator\Command\Generate->OCA\PreviewGenerator\Command\{closure}() at /var/www/nextcloud/lib/private/User/Manager.php:632
2023-11-22T03:08:01+00:00  OC\User\Manager->callForSeenUsers() at /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php:137
2023-11-22T03:08:01+00:00  OCA\PreviewGenerator\Command\Generate->execute() at /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php:298
2023-11-22T03:08:01+00:00  Symfony\Component\Console\Command\Command->run() at /var/www/nextcloud/3rdparty/symfony/console/Application.php:1040
2023-11-22T03:08:01+00:00  Symfony\Component\Console\Application->doRunCommand() at /var/www/nextcloud/3rdparty/symfony/console/Application.php:301
2023-11-22T03:08:01+00:00  Symfony\Component\Console\Application->doRun() at /var/www/nextcloud/3rdparty/symfony/console/Application.php:171
2023-11-22T03:08:01+00:00  Symfony\Component\Console\Application->run() at /var/www/nextcloud/lib/private/Console/Application.php:211
2023-11-22T03:08:01+00:00  OC\Console\Application->run() at /var/www/nextcloud/console.php:100
2023-11-22T03:08:01+00:00  require_once() at /var/www/nextcloud/occ:11
2023-11-22T03:08:01+00:00 
2023-11-22T03:08:01+00:00 preview:generate-all [-p|--path [PATH]] [--] [<user_id>...]
2023-11-22T03:08:01+00:00 
```

**Comment by njchristoffersen** [comment]
I am seeing the same thing. My best guess is that this happens when it gets to photos that have already generated previews for (as my process ran for about 120GiB worth of photos without errors, but then when it got to ones that I have accessed before in browser and on my phone, it spit the error). I'll try:
- rescanning all files, and then retrying the generate previews
if that doesn't work:
- delete all previous image previews, rescan, and then retry the generate previews command.

**Comment by Mat-DB** [comment]
I have the same error on NC28.0.1 and the preview generator app just installed and run number 3 I think.

What is the difference between the following?
```
php occ preview:generate-all
php occ preview:generate --all
```

**Comment by njchristoffersen** [comment]
The first is a correct command, the second is a typo that I made. Thank you for catching that and I've edited my previous comment accordingly.

**Comment by joshtrichards** [comment]
I think this *may* be nextcloud/server#36463 which was *just* fixed in nextcloud/server#41067 (Server v27.1.7 and v28.0.3 have the fix).

**Comment by chrisborell** [comment]
Still occuring for me in [Nextcloud Hub 8] (29.0.2)

![Screenshot 2024-06-20 at 10 09 39 am](https://github.com/nextcloud/previewgenerator/assets/52059185/d17cfdcf-966f-4d40-86a8-636c86276486)
